import type {NextPage} from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Problem1 from './components/Problem1';
import {promises as fs} from 'fs';

type HomePageProps = {
  readonly problem1Input: string;
};

const Home: NextPage<HomePageProps> = ({problem1Input}: HomePageProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Take-home assignment solution</h1>
      <h2 className={styles.subtitle}>by David Veszelovszki</h2>
      <p className={styles.description}>
        This is a solution for a take-home assignment in my 2021 job search.
      </p>
      <Problem1 inputString={problem1Input} />
    </div>
  )
}

export async function getStaticProps() {
    /* Load input from files */
    const problem1Input = await fs.readFile('input/input1.txt');

    /* Assemble props from input */
    return {
        props: {
            problem1Input: problem1Input.toString(),
        }
    };
}
export default Home
