import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.title}>Take-home assignment solution</h1>
      <h2 className={styles.subtitle}>by David Veszelovszki</h2>
      <p className={styles.description}>
        This is a solution for a take-home assignment in my 2021 job search.
      </p>
      <section>
        <h1>Assignment #1</h1>
      </section>
    </div>
  )
}

export default Home
